// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockControl.Api.Datos;

#nullable disable

namespace StockControl.Api.Datos.Migraciones
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827011850_PuestosCaja")]
    partial class PuestosCaja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockControl.Dominio.Caja", b =>
                {
                    b.Property<int>("IdCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCaja"));

                    b.Property<int>("CantidadVentas")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCierre")
                        .HasColumnType("integer");

                    b.Property<int>("IdLocal")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUsuarioCierre")
                        .HasColumnType("integer");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NombreCierre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("NroCaja")
                        .HasColumnType("integer");

                    b.Property<string>("TipoDesglose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Total")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("IdCaja");

                    b.HasIndex("IdLocal", "IdCierre");

                    b.HasIndex("IdLocal", "NroCaja");

                    b.ToTable("Cajas", (string)null);
                });

            modelBuilder.Entity("StockControl.Dominio.Configuracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdLocal")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdLocal", "Clave")
                        .IsUnique();

                    b.ToTable("Configuracion", (string)null);
                });

            modelBuilder.Entity("StockControl.Dominio.GrupoProductos", b =>
                {
                    b.Property<int>("IdGrupoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGrupoProducto"));

                    b.Property<decimal>("Costo")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal>("Ganancia")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)");

                    b.Property<bool>("GananciaIndividual")
                        .HasColumnType("boolean");

                    b.Property<int>("IdLocal")
                        .HasColumnType("integer");

                    b.Property<string>("NombreGrupo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioGrupo")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("IdGrupoProducto");

                    b.ToTable("GrupoProductos", (string)null);
                });

            modelBuilder.Entity("StockControl.Dominio.InformeVenta", b =>
                {
                    b.Property<int>("IdInformeVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInformeVenta"));

                    b.Property<decimal>("Descuento")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<bool>("DetalleAdjunto")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdCierre")
                        .HasColumnType("integer");

                    b.Property<int>("IdLocal")
                        .HasColumnType("integer");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MultipleMetodoDePago")
                        .HasColumnType("boolean");

                    b.Property<int>("NroCaja")
                        .HasColumnType("integer");

                    b.Property<string>("PrecioCosto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("IdInformeVenta");

                    b.HasIndex("IdLocal", "Fecha");

                    b.ToTable("InformeVenta", (string)null);
                });

            modelBuilder.Entity("StockControl.Dominio.InformeVentaDetalle", b =>
                {
                    b.Property<int>("IdInformeVentaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInformeVentaDetalle"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(14, 3)
                        .HasColumnType("numeric(14,3)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Costo")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<int>("IdInformeVenta")
                        .HasColumnType("integer");

                    b.Property<int>("IdLocal")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("IdInformeVentaDetalle");

                    b.HasIndex("IdInformeVenta");

                    b.ToTable("InformeVentaDetalle", (string)null);
                });

            modelBuilder.Entity("StockControl.Dominio.Local", b =>
                {
                    b.Property<int>("IdLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLocal"));

                    b.Property<string>("EstadoAbono")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("Vence")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdLocal");

                    b.ToTable("Locales", (string)null);
                });

            modelBuilder.Entity("StockControl.Dominio.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdLocal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MetodosPago", (string)null);
                });

            modelBuilder.Entity("StockControl.Dominio.OcupacionCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Desde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdLocal")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("NroCaja")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdLocal", "NroCaja", "IdUsuario")
                        .IsUnique();

                    b.ToTable("OcupacionesCaja", (string)null);
                });

            modelBuilder.Entity("StockControl.Dominio.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(14, 3)
                        .HasColumnType("numeric(14,3)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Costo")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTimeOffset?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GananciaIndividual")
                        .HasColumnType("boolean");

                    b.Property<int>("IdGrupoProducto")
                        .HasColumnType("integer");

                    b.Property<int>("IdLocal")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<bool>("ProductoSector")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ValorGanancia")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdLocal", "Codigo")
                        .IsUnique();

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("StockControl.Dominio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HashClave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("StockControl.Dominio.UsuarioLocal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdLocal")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario", "IdLocal")
                        .IsUnique();

                    b.ToTable("UsuarioLocales", (string)null);
                });

            modelBuilder.Entity("StockControl.Dominio.InformeVentaDetalle", b =>
                {
                    b.HasOne("StockControl.Dominio.InformeVenta", null)
                        .WithMany("Detalles")
                        .HasForeignKey("IdInformeVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockControl.Dominio.InformeVenta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
